# Generated by Django 5.2.1 on 2025-06-20 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('busapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bus',
            name='departure_time',
            field=models.TimeField(auto_now_add=True, null=True),
        ),
    ]
