# Generated by Django 5.2.1 on 2025-06-20 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('busapp', '0002_alter_bus_departure_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bus',
            name='departure_time',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
