# Generated by Django 5.2.1 on 2025-06-21 10:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('busapp', '0003_alter_bus_departure_time'),
    ]

    operations = [
        migrations.CreateModel(
            name='BUsRoute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Date', models.DateField(blank=True, null=True)),
                ('bus', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='busapp.bus')),
                ('route', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='busapp.route')),
            ],
        ),
    ]
