# Generated by Django 5.2.1 on 2025-06-23 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('busapp', '0005_bus_user_busoperator_user_busroute_from_location_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bus',
            name='fare',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
