# Generated by Django 5.2.1 on 2025-06-23 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('busapp', '0006_bus_fare'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bus',
            name='fare',
        ),
        migrations.AddField(
            model_name='route',
            name='fare',
            field=models.IntegerField(default=0),
        ),
    ]
