# Generated by Django 5.2.1 on 2025-06-27 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('busapp', '0007_remove_bus_fare_route_fare'),
    ]

    operations = [
        migrations.CreateModel(
            name='SeatBooking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('nrc', models.CharField(max_length=50)),
                ('phone', models.CharField(max_length=20)),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('seat_number', models.CharField(max_length=5)),
                ('fare', models.DecimalField(decimal_places=2, max_digits=6)),
            ],
        ),
    ]
