# Generated by Django 5.2.1 on 2025-06-28 02:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('busapp', '0008_seatbooking'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seatbooking',
            name='time',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
