# Generated by Django 5.2.1 on 2025-06-28 03:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('busapp', '0009_alter_seatbooking_time'),
    ]

    operations = [
        migrations.RenameField(
            model_name='busroute',
            old_name='Date',
            new_name='date',
        ),
    ]
