# Generated by Django 5.2.1 on 2025-06-29 02:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('busapp', '0010_rename_date_busroute_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bus',
            name='bus_number',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
