# Generated by Django 5.2.1 on 2025-06-30 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('busapp', '0012_alter_bus_route'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bus',
            name='bus_type',
            field=models.CharField(blank=True, choices=[('vip', 'VIP'), ('normal', 'Normal')], default='normal', max_length=50, null=True),
        ),
    ]
