# Generated by Django 5.2.1 on 2025-07-03 04:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('busapp', '0013_alter_bus_bus_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='busroute',
            name='price',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
