# Generated by Django 5.2.1 on 2025-07-03 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('busapp', '0014_busroute_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='busroute',
            name='time',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
