# Generated by Django 5.2.1 on 2025-07-10 09:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('busapp', '0016_seatbooking_busroute'),
    ]

    operations = [
        migrations.CreateModel(
            name='SeatBook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_available', models.BooleanField(default=True)),
                ('bus_number', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='busapp.bus')),
                ('route', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='busapp.busroute')),
                ('seat_number', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='busapp.seat')),
            ],
        ),
    ]
