# Generated by Django 5.2.1 on 2025-07-11 02:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('busapp', '0017_seatbook'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seatbook',
            name='bus_number',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='busapp.bus'),
        ),
        migrations.AlterField(
            model_name='seatbook',
            name='route',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='busapp.busroute'),
        ),
        migrations.AlterField(
            model_name='seatbook',
            name='seat_number',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='busapp.seat'),
        ),
    ]
