# Generated by Django 5.2.1 on 2025-07-12 03:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('busapp', '0018_alter_seatbook_bus_number_alter_seatbook_route_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='seatbook',
            name='seat_status',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
