# Generated by Django 5.2.1 on 2025-07-13 05:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('busapp', '0019_seatbook_seat_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='seatbook',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='seatbook',
            name='nrc',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='seatbook',
            name='phone',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
