# Generated by Django 5.2.1 on 2025-07-17 03:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('busapp', '0020_seatbook_name_seatbook_nrc_seatbook_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='seatbook',
            name='amount',
            field=models.IntegerField(default=0),
        ),
    ]
