# Generated by Django 5.2.1 on 2025-07-17 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('busapp', '0021_seatbook_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='seatbook',
            name='booked_date',
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
