# Generated by Django 5.2.1 on 2025-07-24 04:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('busapp', '0022_seatbook_booked_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='busroute',
            name='path',
            field=models.TextField(blank=True, null=True),
        ),
    ]
