# Generated by Django 5.2.1 on 2025-07-26 03:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('busapp', '0023_busroute_path'),
    ]

    operations = [
        migrations.AddField(
            model_name='seatbook',
            name='gender',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='seatbook',
            name='special_request',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='seatbook',
            name='traveller_type',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
